In [49]:
import os
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Classes: ['N': 0, 'S': 1, 'V': 2, 'F': 3, 'Q': 4]

In [42]:
mit_train = np.loadtxt('../data/mitbih_train.csv', delimiter=',')
mit_train.shape

(87554, 188)

In [44]:
mit_test = np.loadtxt('../data/mitbih_test.csv', delimiter=',')
mit_test.shape

(21892, 188)

In [47]:
X_train, y_train = mit_train[:, :-1], mit_train[:,-1].astype(int)

X_train.shape, np.unique(y_train), np.bincount(y_train)

((87554, 187),
 array([0, 1, 2, 3, 4]),
 array([72471,  2223,  5788,   641,  6431]))

In [48]:
X_test, y_test = mit_test[:, :-1], mit_test[:,-1].astype(int)

X_test.shape, np.unique(y_test), np.bincount(y_test)

((21892, 187),
 array([0, 1, 2, 3, 4]),
 array([18118,   556,  1448,   162,  1608]))